version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2
    AWS_ACCOUNT_ID: 440744225243
    IMAGE_REPO_NAME: bbc  # ECR 리포지토리 이름
    IMAGE_TAG: latest

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com || echo "Failed to get ECR login password"
      - docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com || echo "Docker login failed"
      - echo Installing kubectl...
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.27.6/2023-10-17/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      - echo Configuring kubectl for EKS...
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name eks  # EKS 클러스터 이름 필요
      - kubectl get pod --all-namespaces

  pre_build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building React App...
      - npm run build  # React 앱 빌드

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Building Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .  # React 앱이 포함된 Docker 이미지 빌드
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  # ECR로 태그
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG  # ECR로 푸시
      - echo Deploying to EKS...
      - AWS_ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - DATE=$(date)
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' ./EKS/deployment.yaml
      - sed -i.bak 's#DATE_STRING#'"$DATE"'#' ./EKS/deployment.yaml
      - kubectl apply -f ./EKS/deployment.yaml
      - kubectl apply -f ./EKS/service.yaml

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'build'  # 빌드된 React 앱이 위치한 디렉토리
