version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_KAKAO_API_KEY=${REACT_APP_KAKAO_API_KEY}
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
