apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotrank-fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotrank-fe1
  template:
    metadata:
      labels:
        app: spotrank-fe1
    spec:
      containers:
        - name: spotrank-fe1
          image: 440744225243.dkr.ecr.ap-northeast-2.amazonaws.com/bbc:front  # 이미지 URI는 `buildspec.yml`에서 동적으로 치환됩니다.
          ports:
            - containerPort: 80
          imagePullPolicy: Always  # 항상 최신 이미지를 사용
          env:
            - name: REACT_APP_KAKAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: spotrank-fe-secret
                  key: REACT_APP_KAKAO_API_KEY
            - name: DATE  # 배포 시점 정보
              value: 'DATE_STRING'
